/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as LoginRouteImport } from './routes/login'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedOsIndexRouteImport } from './routes/_authenticated/os.index'
import { Route as AuthenticatedOsAnalyticsRouteImport } from './routes/_authenticated/os.analytics'
import { Route as AuthenticatedOsSchedulerRouteImport } from './routes/_authenticated/os.scheduler'
import { Route as AuthenticatedOsSettingsRouteImport } from './routes/_authenticated/os.settings'
import { Route as AuthenticatedOsTasksRouteImport } from './routes/_authenticated/os.tasks'
import { Route as AuthenticatedOsVmsRouteImport } from './routes/_authenticated/os.vms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOsIndexRoute = AuthenticatedOsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsAnalyticsRoute =
  AuthenticatedOsAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsSchedulerRoute =
  AuthenticatedOsSchedulerRouteImport.update({
    id: '/scheduler',
    path: '/scheduler',
    getParentRoute: () => AuthenticatedOsRoute,
  } as any)
const AuthenticatedOsSettingsRoute = AuthenticatedOsSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsTasksRoute = AuthenticatedOsTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)
const AuthenticatedOsVmsRoute = AuthenticatedOsVmsRouteImport.update({
  id: '/vms',
  path: '/vms',
  getParentRoute: () => AuthenticatedOsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/os': typeof AuthenticatedOsRouteWithChildren
  '/os/analytics': typeof AuthenticatedOsAnalyticsRoute
  '/os/scheduler': typeof AuthenticatedOsSchedulerRoute
  '/os/settings': typeof AuthenticatedOsSettingsRoute
  '/os/tasks': typeof AuthenticatedOsTasksRoute
  '/os/vms': typeof AuthenticatedOsVmsRoute
  '/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/os/analytics': typeof AuthenticatedOsAnalyticsRoute
  '/os/scheduler': typeof AuthenticatedOsSchedulerRoute
  '/os/settings': typeof AuthenticatedOsSettingsRoute
  '/os/tasks': typeof AuthenticatedOsTasksRoute
  '/os/vms': typeof AuthenticatedOsVmsRoute
  '/os': typeof AuthenticatedOsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/_authenticated/os': typeof AuthenticatedOsRouteWithChildren
  '/_authenticated/os/analytics': typeof AuthenticatedOsAnalyticsRoute
  '/_authenticated/os/scheduler': typeof AuthenticatedOsSchedulerRoute
  '/_authenticated/os/settings': typeof AuthenticatedOsSettingsRoute
  '/_authenticated/os/tasks': typeof AuthenticatedOsTasksRoute
  '/_authenticated/os/vms': typeof AuthenticatedOsVmsRoute
  '/_authenticated/os/': typeof AuthenticatedOsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/os'
    | '/os/analytics'
    | '/os/scheduler'
    | '/os/settings'
    | '/os/tasks'
    | '/os/vms'
    | '/os/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/os/analytics'
    | '/os/scheduler'
    | '/os/settings'
    | '/os/tasks'
    | '/os/vms'
    | '/os'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/login'
    | '/register'
    | '/_authenticated/os'
    | '/_authenticated/os/analytics'
    | '/_authenticated/os/scheduler'
    | '/_authenticated/os/settings'
    | '/_authenticated/os/tasks'
    | '/_authenticated/os/vms'
    | '/_authenticated/os/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/os/': {
      id: '/_authenticated/os/'
      path: '/'
      fullPath: '/os/'
      preLoaderRoute: typeof AuthenticatedOsIndexRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/analytics': {
      id: '/_authenticated/os/analytics'
      path: '/analytics'
      fullPath: '/os/analytics'
      preLoaderRoute: typeof AuthenticatedOsAnalyticsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/scheduler': {
      id: '/_authenticated/os/scheduler'
      path: '/scheduler'
      fullPath: '/os/scheduler'
      preLoaderRoute: typeof AuthenticatedOsSchedulerRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/settings': {
      id: '/_authenticated/os/settings'
      path: '/settings'
      fullPath: '/os/settings'
      preLoaderRoute: typeof AuthenticatedOsSettingsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/tasks': {
      id: '/_authenticated/os/tasks'
      path: '/tasks'
      fullPath: '/os/tasks'
      preLoaderRoute: typeof AuthenticatedOsTasksRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
    '/_authenticated/os/vms': {
      id: '/_authenticated/os/vms'
      path: '/vms'
      fullPath: '/os/vms'
      preLoaderRoute: typeof AuthenticatedOsVmsRouteImport
      parentRoute: typeof AuthenticatedOsRoute
    }
  }
}

interface AuthenticatedOsRouteChildren {
  AuthenticatedOsAnalyticsRoute: typeof AuthenticatedOsAnalyticsRoute
  AuthenticatedOsSchedulerRoute: typeof AuthenticatedOsSchedulerRoute
  AuthenticatedOsSettingsRoute: typeof AuthenticatedOsSettingsRoute
  AuthenticatedOsTasksRoute: typeof AuthenticatedOsTasksRoute
  AuthenticatedOsVmsRoute: typeof AuthenticatedOsVmsRoute
  AuthenticatedOsIndexRoute: typeof AuthenticatedOsIndexRoute
}

const AuthenticatedOsRouteChildren: AuthenticatedOsRouteChildren = {
  AuthenticatedOsAnalyticsRoute: AuthenticatedOsAnalyticsRoute,
  AuthenticatedOsSchedulerRoute: AuthenticatedOsSchedulerRoute,
  AuthenticatedOsSettingsRoute: AuthenticatedOsSettingsRoute,
  AuthenticatedOsTasksRoute: AuthenticatedOsTasksRoute,
  AuthenticatedOsVmsRoute: AuthenticatedOsVmsRoute,
  AuthenticatedOsIndexRoute: AuthenticatedOsIndexRoute,
}

const AuthenticatedOsRouteWithChildren = AuthenticatedOsRoute._addFileChildren(
  AuthenticatedOsRouteChildren,
)

interface AuthenticatedRouteChildren {
  AuthenticatedOsRoute: typeof AuthenticatedOsRouteWithChildren
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedOsRoute: AuthenticatedOsRouteWithChildren,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
